#!/bin/sh
# Copyright (C) 2004 Robin Hugh Johnson <robbat2@orbis-terrarum.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# we use their macros
if ! grep 'LF_' /usr/share/aclocal -rlq; then
	echo "Autotoolset not found!"
	exit 1
fi

# needed by new autoconf
mkdir -pv config
# we build it later, but do this to fool automake for now
[ -f README ] || cat README.in >README

# clean up
rm -f config.cache

echo "- aclocal."
aclocal -I m4
echo "- autoconf."
autoconf
echo "- autoheader."
autoheader
echo "- automake."
automake -a
exit
